### ISSUE TITLE
flow generator documentation and source code development

### ISSUE THREAD

**Issue by geoffwoollard** [compSPI/simSPI#121]
@KennethNye contributed this notebook on flow generation https://github.com/compSPI/simSPI/blob/master/notebooks/flow_generator_tutorial.ipynb

@KennethNye is interested in taking this to the next step.

I suggest @ninamiolane @fredericpoitevin there be some guidance/direction given on 

1. Inputs and outputs of modularized functions
2. Test case of a protein-sized object

**Comment by ninamiolane** [comment]
Thanks @geoffwoollard for the message. I will close this issue because @KennethNye PR was merged without code review and without unit-tests, it also made the Lint github workflow fail for several users. Unfortunately, I need to revert the PR and remove the notebook from the master branch. The notebook is still great! But its format is not ready to merge into master yet.

The first step is to resubmit a PR with a jupyter notebook that follows the PR guidelines, i.e. the PR checklist that pops up when someone opens a PR.

Then we can talk about the follow-up steps that you mention. I will close issue for now because it not really actionable, we can open an issue that respects the issue format what?why?where?how? later.

Many thanks!

**Comment by KennethNye** [comment]
@ninamiolane Sorry, I am very new to GitHub and make a bold move without taking considerations of all these detailed rules. I think you are doing the correct thing, I will first make the necessary changes before resubmitting a PR for reviewing. Thanks all @ninamiolane @geoffwoollard .
