### ISSUE TITLE
Redesign simSPI and architecture of Python classes for simulators

### ISSUE THREAD

**Issue by harshit-gupta-cor** [compSPI/simSPI#28]
Continuing the [comment-part-2](https://github.com/compSPI/simSPI/pull/20#pullrequestreview-818530355) of @ninamiolane.

Here is one option for the simulator organization. It is more like the option 1 discussed in that comment. It feels a bit more tidy as pointed by @geoffwoollard. 

<img width="274" alt="image" src="https://user-images.githubusercontent.com/18009768/144932059-f10d6604-b800-4b75-9377-7822bfcfd887.png">

_Simulator.py_: 
This module can have an abstract class of simulator and a simulator factory. The latter points to either linear_simulator or tem_simulator depending on the user specification.

_Dataset_generator.py_: 
This will just call the simulator and is agnostic to the type of simulator. It will generate and save the data. It will mainly call the params_generator to create parameters of the current batch of data (for example  rotation matries, shifts, ctf deofcuses) and will pass them to the simulator. For now, I think the params_genertor for linear and tem simulator can be kept different but we could try to merge them in future. 

_main.py_: 
script to call Dataset_generator.py

_config file_:
How the config is passed to the simulator is being more explicitly discussed in this [issue](https://github.com/compSPI/simSPI/issues/14). An option is, similar to simulator, we can have a basic config object with common variables, and then specific tem and linear config object inherited from this object with their own specific variable names. Since both the simulators are being developed and are not final, there is value to do this step at the end when variable names for both the simulators will be known and the final design of the project will be ready.

**Comment by geoffwoollard** [comment]
On 28 Jan 2022 Harshit and I met and chatted about how the differential [linear simulator](https://github.com/compSPI/simSPI/tree/master/simSPI/linear_simulator) and TEM simulator could come together.
* Wait until dust clears on both of them (week or two?). Then do refactor in intentional way after meetings with Nina, Fred, etc
* Follow general directory structure suggested by Harshit [above](https://github.com/compSPI/simSPI/issues/28#issue-1072666785)
* Dataset_generator to have general code for doing sampling of parameters (e.g. uniform or mixture of gaussians for CTF params, rotational params). Much could be modular (sampling from uniform or gaussian using same general code using distributions). See discussion [here](https://github.com/compSPI/simSPI/issues/35)
* I volunteer to go and refactor TEM simulator code to follow what Harshit did in generality for the linear simulator. Harshit could also do this. Capstone students could also do a first pass.
* config categories will have some general, and some "simulator specific", e.g. aperture in TEM simulator.

**Comment by ninamiolane** [comment]
Plan for merging @harshit-gupta-cor PRs is here:
https://github.com/compSPI/simSPI/pull/20#issuecomment-983853121

Once this is done, we can move on to redesigning simSPI.

**Comment by fredericpoitevin** [comment]
#20 was closed. simSPI refactoring can start fresh.
