### ISSUE TITLE
Splitting utils.py

### ISSUE THREAD

**Issue by harshit-gupta-cor** [compSPI/simSPI#29]
Continuing @fredericpoitevin  [comment](https://github.com/compSPI/simSPI/pull/20/files#r759012414), the [utils.py](https://github.com/harshit-gupta-cor/simSPI/blob/linear_simulator/simSPI/linear_simulator/utils.py) needs to be split up in more meaningful functions:

Here is an option:
_fourier_utils.py_: primal_to_fourier_2d, fourier_to_primal_2d
_math_utils.py_: uniform_to_triangular
_volume_utils.py_: init_cube (initializes a 3d cube)

There are three more functions/objects: normalized_mse, attr_dict, init_data 
which are only used by the test functions in test_linear_simulator.
Should I put these functions in the _test_linear_simulator/utils.py_?

**Comment by fredericpoitevin** [comment]
Thanks @harshit-gupta-cor for opening this issue.

- `primal_to_fourier_2d` and `fourier_to_primal_2d`: those functions will probably be useful in other repos, like reconstructSPI, so I'm reluctant to have them under simSPI - we might not think of them here when we'll need them there. How about a `transforms.py` in ioSPI?
- `uniform_to_triangular`: same, how about a `distributions.py` in ioSPI?

I'm OK with all your other suggestions, namely:
- volume_utils.py: init_cube 
- put the other ones under `test_linear_functions/`, but instead of creating a new `utils.py` file, just put them in whatever already existing file makes the most sense.

What do you think @ninamiolane ?

**Comment by fredericpoitevin** [comment]
Another idea fo `transforms.py` and `distributions.py` would be to have these under `compSPI/compSPI` which would contain all code usable across all the other repos?

**Comment by geoffwoollard** [comment]
Yeah, I think compSPI/comSPI could be about the high level organization of the software engineering practices, classes and functions, types of objects (distributions that can be sampled, and scored), and ways the other repos talk together.

**Comment by harshit-gupta-cor** [comment]
I like the compSPI/compSPI idea. Does this mean we also put git:compSPI in the pip dependency?

**Comment by ninamiolane** [comment]
The problem with putting transforms.py/distributions.py in `compSPI/compSPI` is that this repo is not clean at all, it contains all of our old code. 

We should either:
- (i) clean/reset compSPI/compSPI, 
- or (ii) put transforms.py and distributions.py somewhere else in the meantime.

Additionally, we have code for FFT in ioSPI, that should be refactored with all this.

**Comment by fredericpoitevin** [comment]
Once/If merged, https://github.com/compSPI/compSPI/pull/28 completes (i).

I've created https://github.com/compSPI/ioSPI/issues/45 to address refactor of FFT in ioSPI.

**Comment by fredericpoitevin** [comment]
I am closing this issue, which has been addressed in https://github.com/compSPI/compSPI/pull/27 (closed by https://github.com/compSPI/compSPI/pull/28).
