### ISSUE TITLE
Error when creating conda environment from .yml file

### ISSUE THREAD

**Issue by ninamiolane** [compSPI/simSPI#59]
![Screen Shot 2022-01-28 at 4 25 30 PM](https://user-images.githubusercontent.com/8267869/151638797-2571e368-ada6-43ae-aabf-bea7b391385a.png)

**Comment by geoffwoollard** [comment]
@harshit-gupta-cor @fredericpoitevin did you fix this somewhere, or is it still an issue?

**Comment by geoffwoollard** [comment]
Is it a mac / linux thing?

**Comment by harshit-gupta-cor** [comment]
Sorry, I had checked this command on the sdf cluster of Slac. I don't have direct access to Linux. Maybe I missed something. I am working on to correct it. Sorry for this mess.

**Comment by ninamiolane** [comment]
It was happening on my Mac :/

**Comment by fredericpoitevin** [comment]
Yes we just hid the dust under the rug here: https://github.com/compSPI/simSPI/pull/45

I'll push an environment file that works for Mac.

**Comment by harshit-gupta-cor** [comment]
Great! @ninamiolane I thought you were using linux. Can someone testify if the current environment.yml works for linux? @fredericpoitevin @geoffwoollard

**Comment by fredericpoitevin** [comment]
Yes, the current environment.yml works for Linux, and environment-mac.yml works for Mac.

The difference is that pytorch3d is conda installed on Linux while it needs to be pip installed on Mac (for obscure reasons).

A proper fix will be met when we start building pytorch3d from source instead of using this pre-built approach.
